[bumpver]
current_version = "2024.10.1068-dev"
version_pattern = "YYYY.0M.BUILD[-TAG]"
commit_message = "Bump version {old_version} to {new_version}"
commit = true
tag = true
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"app/build.gradle.kts" = [
    'versionName = "{version}"',
    'versionCode = BUILD'
]
